### ISSUE TITLE
Error with MakePost

### ISSUE THREAD

**Issue by reeesh96** [ghackett21/gig.io#47]
The daisies in my backyard need to be watered. Could someone please do that?
https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwjCvb2bzsDTAhWk5YMKHRThDTYQjRwIBw&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FFrench_formal_garden&psig=AFQjCNEca0NPnMWd6eU6jvtQUAoE3dCoNA&ust=1493244182728163

CreatePost:  13 Place d'Armes, 78000 Versailles, France The daisies in my backyard need to be watered. Could someone please do that?
CreatePost: database error:  { Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Armes, 78000 Versailles, France', 48.8012636, 2.120296499999995, '2017-4-25 22:3' at line 1
    at Query.Sequence._packetToError (/u/data/u92/saxena12/cs407/gig.io/Server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/u/data/u92/saxena12/cs407/gig.io/Server/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/u/data/u92/saxena12/cs407/gig.io/Server/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/u/data/u92/saxena12/cs407/gig.io/Server/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/u/data/u92/saxena12/cs407/gig.io/Server/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/u/data/u92/saxena12/cs407/gig.io/Server/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    --------------------
    at Protocol._enqueue (/u/data/u92/saxena12/cs407/gig.io/Server/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Connection.query (/u/data/u92/saxena12/cs407/gig.io/Server/node_modules/mysql/lib/Connection.js:208:25)
    at createPost (/u/data/u92/saxena12/cs407/gig.io/Server/posts/createPost.js:48:13)
    at module.exports (/u/data/u92/saxena12/cs407/gig.io/Server/posts/createPost.js:33:3)
    at /u/data/u92/saxena12/cs407/gig.io/Server/server.js:289:2
    at Layer.handle [as handle_request] (/u/data/u92/saxena12/cs407/gig.io/Server/node_modules/express/lib/router/layer.js:95:5)
    at next (/u/data/u92/saxena12/cs407/gig.io/Server/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/u/data/u92/saxena12/cs407/gig.io/Server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/u/data/u92/saxena12/cs407/gig.io/Server/node_modules/express/lib/router/layer.js:95:5)
    at /u/data/u92/saxena12/cs407/gig.io/Server/node_modules/express/lib/router/index.js:277:22
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlState: '42000',
  index: 0 }

**Comment by ghackett21** [comment]
The picture url is too long to store in the database

**Comment by ghackett21** [comment]
We should have some way of handling this situation to avoid a crash. There needs to be a check for the length of the image address and a message should be displayed saying the address is too long.

**Comment by 007austin** [comment]
Fixed it, makepost now does not allow the user to submit an image link longer than 99 characters. 100 characters made it crash, but 99 works okay.
